name: my second action job
on: push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: List repo files
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
          
      - name: List repo files again
        run: ls -ltra