name: my second action job
on: push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: Execute Cowsay CMD
        run: Cowsay -f dragon "Run for cover, You are a drag....GRRR" >> dragon.txt
      - name: Test file Exists
        run: grep -i "dragon" dragon.txt
      - name: Read File
        run: cat dragon.txt
      - name: checkout Repo files
        run: ls