name: my second action job
on: push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: grant permission to script file
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh

      - name: List repo files
        run: ls -ltra

