name: exploring workflow filters
on:
  workflow_dispatch:
#  schedule:
#  - cron: "*/59 * * * *"
  push:
#        branches-ignore:
#        - feature/*
#        - test/**
    branches:
     - main
     - '!feature/*'
  pull_request:
    types:
     - opened
     - closed
    paths-ignore:
     - README.md
    branches:
     - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}

#[skip ci]
#[ci skip]
#[no ci]
#[skip actions]
#[actions skip]

#skip-checks:true